//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Source: api/v1alpha1 (api/v1alpha1 interfaces and types)
//
// Sprint 2 note: this file would normally be produced by
//   controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
// It is hand-authored here because controller-gen is not available in the
// Sprint 2 dev environment. The content is mechanically correct for the
// types defined in apoharacontextforgecluster_types.go.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties from this object to another object of the
// same type that is provided as a pointer.
func (in *ApohraContextForgeCluster) DeepCopyInto(out *ApohraContextForgeCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ApohraContextForgeCluster and returns it.
func (in *ApohraContextForgeCluster) DeepCopy() *ApohraContextForgeCluster {
	if in == nil {
		return nil
	}
	out := new(ApohraContextForgeCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ApohraContextForgeCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties from this object to another object of the
// same type that is provided as a pointer.
func (in *ApohraContextForgeClusterList) DeepCopyInto(out *ApohraContextForgeClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApohraContextForgeCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ApohraContextForgeClusterList and returns it.
func (in *ApohraContextForgeClusterList) DeepCopy() *ApohraContextForgeClusterList {
	if in == nil {
		return nil
	}
	out := new(ApohraContextForgeClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ApohraContextForgeClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of ApohraContextForgeClusterSpec.
func (in *ApohraContextForgeClusterSpec) DeepCopyInto(out *ApohraContextForgeClusterSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ApohraContextForgeClusterSpec and returns it.
func (in *ApohraContextForgeClusterSpec) DeepCopy() *ApohraContextForgeClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ApohraContextForgeClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ApohraContextForgeClusterStatus.
func (in *ApohraContextForgeClusterStatus) DeepCopyInto(out *ApohraContextForgeClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ApohraContextForgeClusterStatus and returns it.
func (in *ApohraContextForgeClusterStatus) DeepCopy() *ApohraContextForgeClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ApohraContextForgeClusterStatus)
	in.DeepCopyInto(out)
	return out
}
